### ISSUE TITLE
E&P Company Leasing Procedure

### ISSUE THREAD

**Issue by yixinsun1216** [yixinsun1216/covertoperations_manual#4]
Goal: figure out what oil and gas companies publicly say they do when it comes to mineral leasing. 

Start with 10Ks for publicly traded E&P companies on this list and make note of their language surrounding lease acquisitions. 10Ks are in depth annual reports filed by a company to the SEC that contains information like financial statements, organization structure, new ventures, etc. 

These reports can be found on the company's website, under Investor information, SEC filings, or Annual Reports. For example, Chesapeake's filings are [here](http://www.chk.com/investors/sec-filings). Look through the 10Ks for the last couple of years and write up a note for each company. Some things to pay attention for are:

- Do they use landmen, do they have an internal land services division, or do they seem secretive about their operations? For example, Chesapeake lists "Chesapeake Land Development Company , L.L.C" as a subsidiary. 
- Do they target specific areas to expand to?
- Do they mention how difficult it is to find leases or expand?

**Comment by tcovert** [comment]
hi @kviraj2  

Task Overview:
- read each of these 10-Ks, with a specific focus on what management says about mineral leasing and land acquisition (like when they buy leases or producing acreage from other companies)
- write a paragraph or so of high level summary, and paste in quotes as you see appropriate
- do one of these "comment boxes" per 10-K

**Comment by tcovert** [comment]
hi @kviraj2 

thanks for doing the pioneer and chesapeake writeups.  can you do the same for El Paso/EP - they are one of the bigger lessees in our data?  There will be a change in corporate ownership sometime between 2010 and 2015 so keep your eye out for that.  To the extent possible, make sure you are looking at El Paso/EP's upstream business and not their midstream or pipeline businesses.
